services:
  dbxy:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgresx
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: studentdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresx -d studentdb"]
      interval: 2s
      timeout: 5s
      retries: 5

  backendx:
    image: ajmat0001/student-app-backend:latest
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      dbxy:
        condition: service_healthy

  frontendx:
    image: ajmat0001/student-app-frontend:latest
    build: ./frontend
    ports:
      - "3000:80"

  pgwebxy:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://postgresx:mypassword@dbxy:5432/studentdb?sslmode=disable
    depends_on:
      dbxy:
        condition: service_healthy
